include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: error
    prefer_const_constructors: warning
    prefer_final_locals: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true
    avoid_dynamic_calls: true
    use_super_parameters: true
